version: '3.8'
services:
  ros2_node_1:
    image: osrf/ros:jazzy-desktop-full
    container_name: ros2_node_1
    command: ros2 run demo_nodes_cpp talker
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=16
    volumes:
      - /dev:/dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  ros2_node_2:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_node_2
    command: ros2 run demo_nodes_cpp listener
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=16
    volumes:
      - /dev:/dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
