apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros2-humble-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ros-humble-test
  template:
    metadata:
      labels:
        app: ros-humble-test
    spec:
      containers:
      - name: ros-humble-test
        image: ros2_humble_test
        command: ["/bin/bash", "-c", "/opt/ros/humble/setup.bash && ros2 run demo_nodes_cpp listener "]
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ros-humble-service
spec:
  selector:
    app: ros-humble-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080